-- The service uses UUIDs generated by the API, while keeping a database
-- default for operators inserting a row directly during maintenance.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS "logs" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "timestamp" timestamptz NOT NULL,
  "level" text NOT NULL CHECK ("level" IN ('debug', 'info', 'warn', 'error')),
  "service" text NOT NULL CHECK (length("service") > 0),
  "message" text NOT NULL CHECK (length("message") > 0),
  "attributes" jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof("attributes") = 'object'),
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- A unique index on a hypertable must include the partitioning column.
SELECT create_hypertable('logs', 'timestamp', if_not_exists => TRUE);

CREATE UNIQUE INDEX IF NOT EXISTS "logs_id_timestamp_uidx"
  ON "logs" ("id", "timestamp");

-- The first index serves the unfiltered cursor path and is also useful for
-- time-bounded aggregates. Service/level indexes serve the common dashboard
-- filters without requiring a scan of all chunks.
CREATE INDEX IF NOT EXISTS "logs_timestamp_id_idx"
  ON "logs" ("timestamp" DESC, "id" DESC);
CREATE INDEX IF NOT EXISTS "logs_service_timestamp_id_idx"
  ON "logs" ("service", "timestamp" DESC, "id" DESC);
CREATE INDEX IF NOT EXISTS "logs_level_timestamp_id_idx"
  ON "logs" ("level", "timestamp" DESC, "id" DESC);
CREATE INDEX IF NOT EXISTS "logs_attributes_gin_idx"
  ON "logs" USING GIN ("attributes" jsonb_path_ops);
CREATE INDEX IF NOT EXISTS "logs_message_trgm_idx"
  ON "logs" USING GIN ("message" gin_trgm_ops);
